import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import dynamic from "next/dynamic";
import { useEffect, useRef, useState } from "react";

import {
	LinkedinLogoIcon,
	GithubLogoIcon,
	InstagramLogoIcon,
	ArrowSquareOutIcon,
	EyeIcon,
	YoutubeLogoIcon,
	TwitterLogoIcon,
} from "@phosphor-icons/react";

import styles from "../styles/Home.module.css";

const CountUp = dynamic(() => import("react-countup"), { ssr: false });

const Home: NextPage<{ views: number }> = ({ views }) => {
	const [isCounted, setIsCounted] = useState(false);
	const viewsCardRef = useRef<HTMLDivElement>(null);

	useEffect(() => {
		const el = viewsCardRef.current;
		if (!el) return;

		const observer = new IntersectionObserver(
			([entry]) => {
				if (entry?.isIntersecting) {
					setIsCounted(true);
				}
			},
			{ threshold: 0.2 },
		);

		observer.observe(el);
		return () => observer.disconnect();
	}, []);

	return (
		<div className={styles.container}>
			<Head>
				<title>Daniel Costa | Software Engineer</title>
				<meta name="description" content="Generated by Daniel Costa" />
			</Head>

			<main className={styles.main}>
				<Image
					src="/hero.png"
					width={200}
					height={200}
					alt="Picture of Daniel Costa"
					className={styles.picture}
					priority
				/>

				<div className={styles.info}>
					<h1 className={styles.title}>Daniel Costa</h1>
					<p className={styles.description}>Software Engineer</p>
				</div>

				<div className={styles.row}>
					<div className={styles.grid}>
						<a
							href="https://linkedin.com/in/danielcunhac"
							className={styles.card}
						>
							<LinkedinLogoIcon size={24} weight="duotone" />
							<span>/in/danielcunhac</span>
							<ArrowSquareOutIcon size={24} />
						</a>
						<a href="https://github.com/danicunhac" className={styles.card}>
							<GithubLogoIcon size={24} weight="duotone" />
							<span>/danicunhac</span>
							<ArrowSquareOutIcon size={24} />
						</a>
						<a href="https://instagram.com/dancunhac" className={styles.card}>
							<InstagramLogoIcon size={24} weight="duotone" />
							<span>@dancunhac</span>
							<ArrowSquareOutIcon size={24} />
						</a>
					</div>
					<div className={styles.grid}>
						<a href="https://youtube.com/@danicunhac" className={styles.card}>
							<YoutubeLogoIcon size={24} weight="duotone" />
							<span>/@danicunhac</span>
							<ArrowSquareOutIcon size={24} />
						</a>
						<a href="https://twitter.com/danicunhac" className={styles.card}>
							<TwitterLogoIcon size={24} weight="duotone" />
							<span>@danicunhac</span>
							<ArrowSquareOutIcon size={24} />
						</a>
						<CountUp
							decimal="."
							separator="."
							start={isCounted ? 0 : undefined}
							end={views}
							redraw={true}
							duration={views * 0.1}
						>
							{({ countUpRef }) => (
								<div ref={viewsCardRef} className={styles.card}>
									<EyeIcon size={24} weight="duotone" />
									<span>Views</span>
									<span className={styles.count} ref={countUpRef} />
								</div>
							)}
						</CountUp>
					</div>
				</div>
			</main>
		</div>
	);
};

export default Home;
